name: Build pake app

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'https://next.starxv.com'
        required: true
      name:
        description: '星辰云'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Build pake app
        run: |
          npx pake "${{ github.event.inputs.url }}" --name "${{ github.event.inputs.name }}" --targets windows

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pake-app
          path: pake-*  # 打包后生成的文件名通常以 pake 开头
