name: Build 星辰云 with Pake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build pake app with tw93/action-pake
        uses: tw93/action-pake@v1
        with:
          url: https://next.starxv.com
          name: 星辰云
          platform: win

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 星辰云
          path: dist/**/*
